"""
Django settings for landingpage project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv
from django.core.exceptions import ImproperlyConfigured
from urllib.parse import unquote, urlparse

try:
    import sentry_sdk
    from sentry_sdk.integrations.django import DjangoIntegration
except ImportError:  # pragma: no cover - handled by dependency installation
    sentry_sdk = None
    DjangoIntegration = None


def env_bool(name, default=False):
    value = os.getenv(name)
    if value is None:
        return default
    return str(value).strip().lower() in {"1", "true", "yes", "on"}


def env_int(name, default=0):
    value = os.getenv(name)
    if value is None or not str(value).strip():
        return default
    return int(str(value).strip())


def env_list(name, default=None):
    value = os.getenv(name)
    if value is None:
        return list(default or [])
    return [item.strip() for item in value.split(',') if item.strip()]


def env_pairs(name):
    pairs = []
    for item in env_list(name):
        if ':' in item:
            label, value = item.split(':', 1)
            pairs.append((label.strip(), value.strip()))
        else:
            pairs.append((item, item))
    return pairs


def database_config_from_url(url):
    parsed = urlparse(url)
    scheme = (parsed.scheme or '').lower()
    engine_map = {
        'postgres': 'django.db.backends.postgresql',
        'postgresql': 'django.db.backends.postgresql',
        'pgsql': 'django.db.backends.postgresql',
        'sqlite': 'django.db.backends.sqlite3',
        'sqlite3': 'django.db.backends.sqlite3',
    }
    engine = engine_map.get(scheme)
    if not engine:
        raise ValueError(f'Unsupported DATABASE_URL scheme: {scheme or "<empty>"}')

    if engine == 'django.db.backends.sqlite3':
        db_name = unquote(parsed.path or '')
        if db_name in {'', '/', '/:memory:'}:
            db_name = ':memory:'
        else:
            db_name = db_name.lstrip('/')
            if not os.path.isabs(db_name):
                db_name = str(BASE_DIR / db_name)
        return {
            'ENGINE': engine,
            'NAME': db_name,
        }

    config = {
        'ENGINE': engine,
        'NAME': unquote((parsed.path or '').lstrip('/')),
        'USER': unquote(parsed.username or ''),
        'PASSWORD': unquote(parsed.password or ''),
        'HOST': parsed.hostname or '',
        'PORT': str(parsed.port or ''),
    }
    if env_bool('DATABASE_SSL_REQUIRE', True):
        config['OPTIONS'] = {'sslmode': 'require'}
    return config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# load environment variables from .env at project root
load_dotenv(str(BASE_DIR / '.env'))

DEFAULT_AUTO_FIELD = "django.db.models.AutoField"

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-a!3-g6epp3h*4*!e!1w=0lqmrh+d0z2)s099c547u72=pb2q7s')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool('DEBUG', True)

configured_allowed_hosts = env_list('ALLOWED_HOSTS')
if configured_allowed_hosts:
    ALLOWED_HOSTS = configured_allowed_hosts
elif DEBUG:
    ALLOWED_HOSTS = ['*']
else:
    ALLOWED_HOSTS = ['127.0.0.1', 'localhost']

CSRF_TRUSTED_ORIGINS = [origin.rstrip('/') for origin in env_list('CSRF_TRUSTED_ORIGINS')]
CSRF_FAILURE_VIEW = 'landingpage.csrf.csrf_failure'


# Application definition

INSTALLED_APPS = [
    'unfold',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # startapps:
    'apps.accounts', 
    'apps.chat',
    'apps.clients',
    'apps.news',
    'apps.operations',
   

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'landingpage.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'landingpage.context_processors.site_contact',
            ],
        },
    },
]

WSGI_APPLICATION = 'landingpage.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

database_url = (os.getenv('DATABASE_URL') or '').strip()
if env_bool('REQUIRE_DATABASE_URL', False) and not database_url:
    raise ImproperlyConfigured('DATABASE_URL must be set when DEBUG=False.')
DATABASES = {
    'default': database_config_from_url(database_url) if database_url else {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}
DATABASES['default']['CONN_MAX_AGE'] = env_int('DATABASE_CONN_MAX_AGE', 60)
DATABASES['default']['CONN_HEALTH_CHECKS'] = env_bool('DATABASE_CONN_HEALTH_CHECKS', not DEBUG)
CACHES = {
    'default': {
        'BACKEND': os.getenv('CACHE_BACKEND', 'django.core.cache.backends.locmem.LocMemCache'),
        'LOCATION': os.getenv('CACHE_LOCATION', 'insights-website-cache'),
        'TIMEOUT': env_int('CACHE_DEFAULT_TIMEOUT', 300),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
MEDIA_URL = '/media/'

DJANGO_ADMIN_URL=os.getenv('DJANGO_ADMIN_URL')

# Project-level static and template folders
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Optional STATIC_ROOT for collectstatic (useful for deployments)
STATIC_ROOT = BASE_DIR / 'staticfiles'
STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedStaticFilesStorage',
    },
}
WHITENOISE_USE_FINDERS = True
MEDIA_ROOT = BASE_DIR / 'media'
FILE_UPLOAD_PERMISSIONS = 0o640
FILE_UPLOAD_DIRECTORY_PERMISSIONS = 0o750
FILE_UPLOAD_MAX_MEMORY_SIZE = env_int('FILE_UPLOAD_MAX_MEMORY_SIZE', 2 * 1024 * 1024)
DATA_UPLOAD_MAX_MEMORY_SIZE = env_int('DATA_UPLOAD_MAX_MEMORY_SIZE', 10 * 1024 * 1024)


# Email (newsletter)
EMAIL_BACKEND = os.getenv(
    'EMAIL_BACKEND',
    'django.core.mail.backends.console.EmailBackend',
)
EMAIL_HOST = os.getenv('EMAIL_HOST', '')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', os.getenv('BREVO_SMTP_USER', ''))
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', os.getenv('BREVO_SMTP_PASSWORD', ''))
EMAIL_USE_TLS = env_bool('EMAIL_USE_TLS')
EMAIL_USE_SSL = env_bool('EMAIL_USE_SSL')
EMAIL_TIMEOUT = env_int('EMAIL_TIMEOUT', 10)
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL')
SITE_URL = os.getenv('SITE_URL', 'http://localhost:8000').rstrip('/')
LOGIN_REDIRECT_URL = '/dashboard/'
LOGOUT_REDIRECT_URL = '/'
MOBILE_APP_REMEMBER_ME_SESSION_AGE = int(os.getenv('MOBILE_APP_REMEMBER_ME_SESSION_AGE', str(60 * 60 * 24 * 90)))

# Turnstile (for contact form and sign up pages)
TURNSTILE_SITE_KEY = os.getenv('TURNSTILE_SITE_KEY', '')
TURNSTILE_SECRET_KEY = os.getenv('TURNSTILE_SECRET_KEY', '')
TURNSTILE_VERIFY_URL = os.getenv('TURNSTILE_VERIFY_URL', 'https://challenges.cloudflare.com/turnstile/v0/siteverify')

# Newsletter sender (use a dedicated address for outgoing newsletters)
NEWSLETTER_FROM_EMAIL = os.getenv('NEWSLETTER_FROM_EMAIL', DEFAULT_FROM_EMAIL)

# Contact / support
CONTACT_RECIPIENT = os.getenv('CONTACT_RECIPIENT')
SUPPORT_EMAIL = os.getenv('SUPPORT_EMAIL', CONTACT_RECIPIENT)
COMPANY_NOTIFICATION_EMAIL = os.getenv('COMPANY_NOTIFICATION_EMAIL', 'company@mirandainsights.com')
SERVER_EMAIL = os.getenv('SERVER_EMAIL', DEFAULT_FROM_EMAIL or 'server@localhost')
EMAIL_SUBJECT_PREFIX = os.getenv('EMAIL_SUBJECT_PREFIX', '[Miranda Insights] ')
ADMINS = env_pairs('ADMINS')
MANAGERS = env_pairs('MANAGERS') if env_list('MANAGERS') else ADMINS
SENTRY_DSN = os.getenv('SENTRY_DSN', '').strip()
SENTRY_ENVIRONMENT = os.getenv('SENTRY_ENVIRONMENT', 'production').strip() or 'production'
SENTRY_RELEASE = os.getenv('SENTRY_RELEASE', '').strip() or None
SENTRY_SEND_DEFAULT_PII = env_bool('SENTRY_SEND_DEFAULT_PII', False)
SENTRY_TRACES_SAMPLE_RATE = float(os.getenv('SENTRY_TRACES_SAMPLE_RATE', '0'))
SENTRY_PROFILES_SAMPLE_RATE = float(os.getenv('SENTRY_PROFILES_SAMPLE_RATE', '0'))

THROTTLE_ENABLED = env_bool('THROTTLE_ENABLED', True)
THROTTLE_CACHE_ALIAS = os.getenv('THROTTLE_CACHE_ALIAS', 'default')
OUTBOUND_DELIVERY_MODE = os.getenv('OUTBOUND_DELIVERY_MODE', 'sync' if DEBUG else 'queue').strip().lower()
OUTBOUND_WORKER_SLEEP_SECONDS = float(os.getenv('OUTBOUND_WORKER_SLEEP_SECONDS', '5'))
LOGIN_RATE_LIMIT = os.getenv('LOGIN_RATE_LIMIT', '10/10m')
LOGIN_2FA_RATE_LIMIT = os.getenv('LOGIN_2FA_RATE_LIMIT', '10/10m')
SIGNUP_RATE_LIMIT = os.getenv('SIGNUP_RATE_LIMIT', '5/1h')
USERNAME_RECOVERY_RATE_LIMIT = os.getenv('USERNAME_RECOVERY_RATE_LIMIT', '5/1h')
PASSWORD_RESET_RATE_LIMIT = os.getenv('PASSWORD_RESET_RATE_LIMIT', '5/1h')
CONTACT_RATE_LIMIT = os.getenv('CONTACT_RATE_LIMIT', '5/30m')
NEWSLETTER_SUBSCRIBE_RATE_LIMIT = os.getenv('NEWSLETTER_SUBSCRIBE_RATE_LIMIT', '10/1h')
MOBILE_PUSH_DEVICE_RATE_LIMIT = os.getenv('MOBILE_PUSH_DEVICE_RATE_LIMIT', '30/10m')

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = env_bool('USE_X_FORWARDED_HOST', not DEBUG)
CSRF_COOKIE_HTTPONLY = True
SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_SAMESITE = os.getenv('CSRF_COOKIE_SAMESITE', 'Lax')
SESSION_COOKIE_SAMESITE = os.getenv('SESSION_COOKIE_SAMESITE', 'Lax')
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = 'same-origin'
SECURE_CROSS_ORIGIN_OPENER_POLICY = os.getenv('SECURE_CROSS_ORIGIN_OPENER_POLICY', 'same-origin')
SECURE_CROSS_ORIGIN_RESOURCE_POLICY = os.getenv('SECURE_CROSS_ORIGIN_RESOURCE_POLICY', 'same-origin')
X_FRAME_OPTIONS = os.getenv('X_FRAME_OPTIONS', 'DENY')

if not DEBUG:
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_SSL_REDIRECT = env_bool('SECURE_SSL_REDIRECT', True)
    SECURE_HSTS_SECONDS = int(os.getenv('SECURE_HSTS_SECONDS', '31536000'))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = env_bool('SECURE_HSTS_INCLUDE_SUBDOMAINS', True)
    SECURE_HSTS_PRELOAD = env_bool('SECURE_HSTS_PRELOAD', True)

UNFOLD = {
    "SITE_TITLE": "Miranda Insights Admin",
    "SITE_HEADER": "Miranda Insights Admin",
    "SITE_SUBHEADER": "Management Workspace",
    "SITE_ICON": {
        "light": f"{STATIC_URL}pwa/icon-192.png",
        "dark": f"{STATIC_URL}pwa/icon-192.png",
    },
    "SITE_SYMBOL": "monitoring",
    "STYLES": [
        "css/admin-theme.css",
    ],
    "COLORS": {
        "primary": {
            "50": "#eff6ff",
            "100": "#dbeafe",
            "200": "#bfdbfe",
            "300": "#93c5fd",
            "400": "#60a5fa",
            "500": "#3b82f6",
            "600": "#2563eb",
            "700": "#1d4ed8",
            "800": "#1e40af",
            "900": "#1e3a8a",
            "950": "#172554",
        },
    },
}


# custom admin url from env, default to "admin"
DJANGO_ADMIN_URL = os.getenv("DJANGO_ADMIN_URL", "admin").strip("/")


LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'standard': {
            'format': '%(asctime)s %(levelname)s %(name)s %(message)s',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'standard',
        },
        'mail_admins': {
            'level': 'ERROR',
            'class': 'django.utils.log.AdminEmailHandler',
            'include_html': True,
        },
    },
    'root': {
        'handlers': ['console'],
        'level': os.getenv('ROOT_LOG_LEVEL', 'INFO'),
    },
    'loggers': {
        'django.security': {
            'handlers': ['console', 'mail_admins'],
            'level': os.getenv('DJANGO_SECURITY_LOG_LEVEL', 'WARNING'),
            'propagate': False,
        },
        'django.request': {
            'handlers': ['console', 'mail_admins'],
            'level': 'ERROR',
            'propagate': False,
        },
        'apps': {
            'handlers': ['console', 'mail_admins'],
            'level': os.getenv('APP_LOG_LEVEL', 'INFO'),
            'propagate': False,
        },
        'landingpage': {
            'handlers': ['console', 'mail_admins'],
            'level': os.getenv('APP_LOG_LEVEL', 'INFO'),
            'propagate': False,
        },
    },
}


if SENTRY_DSN and sentry_sdk and DjangoIntegration:
    sentry_sdk.init(
        dsn=SENTRY_DSN,
        integrations=[DjangoIntegration()],
        environment=SENTRY_ENVIRONMENT,
        release=SENTRY_RELEASE,
        send_default_pii=SENTRY_SEND_DEFAULT_PII,
        traces_sample_rate=SENTRY_TRACES_SAMPLE_RATE,
        profiles_sample_rate=SENTRY_PROFILES_SAMPLE_RATE,
    )