# Generated by Django 5.2.5 on 2026-04-04 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='outboundjob',
            new_name='operations__status_b805fb_idx',
            old_name='operations_o_status_8dd9f0_idx',
        ),
        migrations.RenameIndex(
            model_name='outboundjob',
            new_name='operations__job_typ_3e9e71_idx',
            old_name='operations_o_job_typ_8beacb_idx',
        ),
    ]
